# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/recist_calc',
                'doc_host': 'https://Lightbridge-KS.github.io',
                'git_url': 'https://github.com/Lightbridge-KS/recist_calc',
                'lib_path': 'recist_calc'},
  'syms': { 'recist_calc.nontarget': { 'recist_calc.nontarget.RecistNonTarget': ( 'nontarget.html#recistnontarget',
                                                                                  'recist_calc/nontarget.py'),
                                       'recist_calc.nontarget.RecistNonTarget.__post_init__': ( 'nontarget.html#recistnontarget.__post_init__',
                                                                                                'recist_calc/nontarget.py')},
            'recist_calc.target': { 'recist_calc.target.RecistTarget': ('target.html#recisttarget', 'recist_calc/target.py'),
                                    'recist_calc.target.RecistTarget.__post_init__': ( 'target.html#recisttarget.__post_init__',
                                                                                       'recist_calc/target.py')},
            'recist_calc.timepoint': { 'recist_calc.timepoint.RecistTimePoint': ( 'timepoint.html#recisttimepoint',
                                                                                  'recist_calc/timepoint.py'),
                                       'recist_calc.timepoint.RecistTimePoint.__post_init__': ( 'timepoint.html#recisttimepoint.__post_init__',
                                                                                                'recist_calc/timepoint.py')}}}
