# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_nontarget.ipynb.

# %% auto 0
__all__ = ['RecistNonTarget']

# %% ../nbs/02_nontarget.ipynb 3
from dataclasses import dataclass, field

# %% ../nbs/02_nontarget.ipynb 6
@dataclass
class RecistNonTarget:
    """
    This class represents the RECIST (Response Evaluation Criteria in Solid Tumors) evaluation 
    for non-target lesions in a given time point.
    """
    category: str = field(init=False)
    unequivocal_progress: bool = None
    disappear_all: bool = None
    is_new_lesion: bool = None
    is_ln_pathological: bool = None
    is_tumor_mk_normalized: bool = None
    
    def __post_init__(self):
        # Check for "Not Evaluable" (NE) condition
        if all(param is None for param in [self.unequivocal_progress, self.disappear_all, self.is_new_lesion]):
            self.category = "NE"
        elif self.unequivocal_progress or self.is_new_lesion:
            self.category = "PD"
        elif self.disappear_all and self.is_tumor_mk_normalized and not self.is_ln_pathological:
            self.category = "CR"
        else:
            self.category = "Non-CR/Non-PD"

